version: "3.9"
services:
  postgres:
    container_name: iqro_database
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - iqro-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    networks:
      - mynet

  python:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iqro_backend
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8002:8000
    restart: on-failure
    env_file:
      - .env
    networks:
      - mynet

volumes:
  iqro-volume:

networks:
  mynet:
    driver: bridge
